### PR TITLE
Race formula

### PR DESCRIPTION
**Pull request by Steptro**
Really large PR implementing the race formula. A lot of extra things were necessary. Some tests needed to be modified or some tests were missing.

Also I added an extra attribute `score` in the Driver class for sorting the result.

### CODE REVIEW

**Comment by Steptro** [comment]
[Implementing race formula to determine result of the race](https://trello.com/c/KeSz8rlc/39-implementing-race-formula-to-determine-result-of-the-race)

**Comment by asettels** [comment]
In Driver at setRaceCraft, you don't throw an exception if the value is below 0/exceeds 100. You do this with speed. Should there be an exception at racecraft?

**Comment by asettels** [comment]
*NOTE: This is a quation* In a lot of getters there was a TODO in the comments (how to determine this value....) You replaced this by returning a value (like 50, or 78). Is this meant to be always the same or should this be a piece of data (from the team member). Can you explain this or add the todo so that we don't forget to do this later?

**Comment by Steptro** [comment]
@asettels this is true, I wanted to do that later because this PR was getting too big. 

Also these 50 and 78 values should come from the JSON. @mvanniekerk wil take care of this. So for now I added a value just to test my implentation

**Pull request merged**
