### PR TITLE
Added Matthijs to README.md

### PR DESCRIPTION
**Pull request by mvanniekerk**
Also changed the folder name to team-photos, because spaces in folder names are bad

### CODE REVIEW

**Comment by Steptro** [comment]
Why are spaces in folder names bad?

**Comment by Steptro** [comment]
Next time remember to put the commit messages in the imperative form ;)

**Comment by mvanniekerk** [comment]
http://superuser.com/questions/29111/what-technical-reasons-exist-for-not-using-space-characters-in-file-names#29117
Never use spaces in file or directory names because of command line difficulties. Besides that, the many different ways you need to know to escape spaces has just too much cognitive load to be worth it, so just use a '_' or a '-' or even a '.'

**Comment by Steptro** [comment]
Cool!

**Pull request merged**
